services:
 server:
   build: ./server
   container_name: words-server
   ports:
    - '5000:5000'
   environment:
    - FRONT_URL=http://127.0.0.1:3000
 front:
   build: ./front
   container_name: words-front
   ports:
    - '3000:3000'